// Generated by scripts/gen-samsung-images.py — do not edit.
// Public product renders from samsung.com's image CDN; see the script for how they were found.

export interface SamsungRender {
  /** Samsung's name for the finish, lower case (`white`, `black`, `gray`, …). */
  colour: string
  url: string
}

export const SAMSUNG_RENDERS: Readonly<Record<string, readonly SamsungRender[]>> = {
  buds3: [
    { colour: "silver", url: "https://images.samsung.com/is/image/samsung/p6pim/uk/2407/gallery/uk-galaxy-buds3-r530-sm-r530nzaaeua-thumb-542217404?$650_519_PNG$" },
  ],
  buds3Fe: [
    { colour: "black", url: "https://images.samsung.com/is/image/samsung/p6pim/de/sm-r420nzkadbt/gallery/de-galaxy-buds3-fe-sm-r420nzkadbt-thumb-548580438?$650_519_PNG$" },
    { colour: "gray", url: "https://images.samsung.com/is/image/samsung/p6pim/us/sm-r420nzaaxar/gallery/us-galaxy-buds3-fe-sm-r420nzaaxar-553270299?$650_519_PNG$" },
  ],
  buds3Pro: [
    { colour: "silver", url: "https://images.samsung.com/is/image/samsung/p6pim/uk/2407/gallery/uk-galaxy-buds3-pro-r630-sm-r630nzaaeua-thumb-542217309?$650_519_PNG$" },
  ],
  buds4: [
    { colour: "black", url: "https://images.samsung.com/is/image/samsung/p6pim/au/s2602/gallery/au-galaxy-buds4-r540-sm-r540nzkaxsa-thumb-550977997?$650_519_PNG$" },
    { colour: "white", url: "https://images.samsung.com/is/image/samsung/p6pim/us/sm-r540nzwaxar/gallery/us-galaxy-buds4-r540-sm-r540nzwaxar-553270291?$650_519_PNG$" },
  ],
  buds4Pro: [
    { colour: "black", url: "https://images.samsung.com/is/image/samsung/p6pim/uk/s2602/gallery/uk-galaxy-buds4-r640-579822-sm-r640nzkaeub-thumb-551034371?$650_519_PNG$" },
    { colour: "pink gold", url: "https://images.samsung.com/is/image/samsung/p6pim/uk/s2602/gallery/uk-galaxy-buds4-r640-sm-r640nzdaeub-thumb-551034243?$650_519_PNG$" },
    { colour: "white", url: "https://images.samsung.com/is/image/samsung/p6pim/us/sm-r640nzwaxar/gallery/us-galaxy-buds4-r640-sm-r640nzwaxar-553270130?$650_519_PNG$" },
  ],
  budsCore: [
    { colour: "white", url: "https://images.samsung.com/is/image/samsung/p6pim/in/sm-r410nzwainu/gallery/in-galaxy-buds-core-r410-sm-r410nzwainu-thumb-547798416?$650_519_PNG$" },
  ],
}
