#!/usr/bin/env python3
"""Regenerate src/drivers/heymelody/catalog.generated.ts from
docs/reference/heymelody-devices.json, docs/reference/heymelody-anc-modes.json,
docs/reference/heymelody-eq-modes.json, docs/reference/heymelody-controls.json
and docs/reference/realme-models.json.

Source: the 137-device productId/name/brand/type catalog extracted from
OppoPodsManager's bundled DeviceModels.json and cross-validated against
HeyTap's own bundled whitelist resource (`res/raw/heymelody_app_whitelist`). Brand casing in the source is
inconsistent ("oppo"/"realme"/"OnePlus") — normalised to lowercase here so
the generated type is a clean 3-value union.

`heymelody-anc-modes.json` is a second, separate source: each model's
`function.noiseReductionMode` array from the same whitelist resource
(its decrypted
`compatWhiteList`), extracted for the 41/82 whitelist entries that carry it —
this is what tells a driver which bit (`protocolIndex`) to set for which named
ANC mode on a *given* model, since that bit position is not fixed across
models (see `src/drivers/heymelody/ancModel.ts`, ported from
Leaf-lsgtky/OppoPods's `DeviceModelRegistry.buildAncOptions`). Only 81/82
whitelist productIds overlap the 137-device catalog; the one that doesn't is
silently skipped here rather than fabricating a catalog entry for it.

`realme-models.json` is a third source, used only for productIds the
HeyTap whitelist does not cover: realme Link's per-model noise items
(from its bundled `headsetRusConfig`), turned into the same
`noiseReductionMode` shape through realme's own item-to-value mapping
(`ItemFactory.java:747-765, 791-810`).

`heymelody-controls.json` carries each model's touch-control `support` masks:
which functions each tap action accepts. The whitelist names actions by its own
UI codes; they are mapped to the wire action here (`WIRE_ACTION`), and masks
that land on the same wire action are OR-ed together.

Usage:
    python3 scripts/gen-heymelody-catalog.py
"""

import json
from pathlib import Path

SOURCE = Path("docs/reference/heymelody-devices.json")
ANC_MODES_SOURCE = Path("docs/reference/heymelody-anc-modes.json")
REALME_MODELS_SOURCE = Path("docs/reference/realme-models.json")
EQ_MODES_SOURCE = Path("docs/reference/heymelody-eq-modes.json")
CONTROLS_SOURCE = Path("docs/reference/heymelody-controls.json")

# HeyTap G8/g.java:596-641: whitelist UI action -> wire action in the 0x0108 records.
WIRE_ACTION = {
    11: 4, 16: 1, 17: 2, 18: 3, 19: 4, 20: 4, 22: 6,
    26: 2, 29: 2, 33: 2, 36: 2, 27: 4, 28: 1, 32: 1, 30: 3, 34: 3, 31: 6, 35: 6,
}

# realme ItemFactory.java:747-765, 791-810: (protocolIndex = log2(value), modeType per ancModel.ts MODE_TYPE_KEY)
REALME_MODES = {
    "ITEM_NOISE_REDUCTION": (0, 5),
    "ITEM_NOISE_CLOSE": (1, 1),
    "ITEM_NOISE_NORMAL": (1, 1),
    "ITEM_NOISE_TRANSPARENT": (2, 2),
}
REALME_LEVELS = {
    "ITEM_DEEP_REDUCTION": (0, 4),
    "ITEM_LIGHT_REDUCTION": (3, 3),
    "ITEM_MEDIUM_REDUCTION": (4, 8),
    "ITEM_SMART_REDUCTION": (5, 7),
}
OUTPUT = Path("src/drivers/heymelody/catalog.generated.ts")

HEADER = """/**
 * Generated by scripts/gen-heymelody-catalog.py from
 * docs/reference/heymelody-devices.json,
 * docs/reference/heymelody-anc-modes.json,
 * docs/reference/heymelody-eq-modes.json,
 * docs/reference/heymelody-controls.json and
 * docs/reference/realme-models.json. Do not hand-edit.
 */

import type { RawAncModeEntry } from './ancModel'

export interface HeyMelodyCatalogEntry {
  productId: string
  name: string
  brand: 'oppo' | 'realme' | 'oneplus'
  type: string
  /** Only present for the subset of models the source whitelist covers (see
   * this file's own generator script for provenance) — absent, not an empty
   * array, when this model's ANC bit layout was never captured. */
  noiseReductionMode?: RawAncModeEntry[]
  /** Built-in EQ presets for this model: `protocolIndex` is the wire id sent
   * with `0x0406`, `modeType` picks the display name (see `eqModes.ts`).
   * Absent when the source whitelist does not cover the model. */
  equalizerMode?: { protocolIndex: number; modeType: number }[]
  /** Custom EQ slot cap; absent means the vendor default (3). */
  customEqMax?: number
  /** Custom-EQ band centres in Hz, for the models whose whitelist entry sets
   * `customEqFrequency` (ten bands, 31 Hz to 16 kHz); absent means the
   * vendor's six-band default. */
  customEqFrequency?: number[]
  /** Per wire tap action, the HeyTap function flags it accepts (see
   * `protocol/gesture.ts`). Absent when the source whitelist does not cover the model. */
  touchSupport?: { action: number; support: number }[]
}

export const HEYMELODY_CATALOG: readonly HeyMelodyCatalogEntry[] = [
"""

FOOTER = """]
"""


def squash(name: str) -> str:
    return "".join(name.lower().split())


def realme_noise_modes(items: list[str]) -> list[dict]:
    """`noiseReductionMode` entries built from a realme model's noise items."""
    levels = [{"protocolIndex": REALME_LEVELS[i][0], "modeType": REALME_LEVELS[i][1]} for i in items if i in REALME_LEVELS]
    modes, seen = [], set()
    for item in items:
        if item not in REALME_MODES or REALME_MODES[item] in seen:
            continue
        seen.add(REALME_MODES[item])
        index, mode_type = REALME_MODES[item]
        entry = {"protocolIndex": index, "modeType": mode_type}
        if item == "ITEM_NOISE_REDUCTION" and levels:
            entry["childrenMode"] = levels
        modes.append(entry)
    return modes


def main() -> None:
    data = json.loads(SOURCE.read_text(encoding="utf-8"))
    anc_data = json.loads(ANC_MODES_SOURCE.read_text(encoding="utf-8"))
    anc_by_product_id = {d["productId"]: d["noiseReductionMode"] for d in anc_data["devices"]}

    touch_by_product_id: dict[str, list[dict]] = {}
    for device in json.loads(CONTROLS_SOURCE.read_text(encoding="utf-8"))["devices"]:
        masks: dict[int, int] = {}
        for control in device["control"]:
            action = WIRE_ACTION.get(control["action"], control["action"])
            masks[action] = masks.get(action, 0) | control["support"]
        touch_by_product_id[device["productId"]] = [{"action": a, "support": m} for a, m in masks.items()]

    eq_by_product_id = {d["productId"]: d for d in json.loads(EQ_MODES_SOURCE.read_text(encoding="utf-8"))["devices"]}

    names = {d["productId"]: d["name"] for d in data["devices"]}
    realme_by_product_id: dict[str, list[dict]] = {}
    realme = json.loads(REALME_MODELS_SOURCE.read_text(encoding="utf-8"))["models"]
    # modelId is not unique (T300 Pro / T500 Pro share 066452): prefer the entry named like ours.
    for model in sorted(realme, key=lambda m: squash(m["model"]) != squash(names.get(m["modelId"], ""))):
        modes = realme_noise_modes(model["noiseItems"])
        if modes:
            realme_by_product_id.setdefault(model["modelId"], modes)

    lines = [HEADER]
    matched_anc = 0
    matched_realme = 0
    matched_eq = 0
    matched_touch = 0
    for device in data["devices"]:
        brand = device["brand"].lower()
        entry = {
            "productId": device["productId"],
            "name": device["name"],
            "brand": brand,
            "type": device["type"],
        }
        nrm = anc_by_product_id.get(entry["productId"])
        if nrm is not None:
            matched_anc += 1
        else:
            nrm = realme_by_product_id.get(entry["productId"])
            if nrm is not None:
                matched_realme += 1
        if nrm is not None:
            entry["noiseReductionMode"] = nrm
        eq = eq_by_product_id.get(entry["productId"])
        if eq is not None:
            matched_eq += 1
            if eq.get("equalizerMode"):
                entry["equalizerMode"] = eq["equalizerMode"]
            if eq.get("customEqMax") is not None:
                entry["customEqMax"] = eq["customEqMax"]
            if eq.get("customEqFrequency"):
                entry["customEqFrequency"] = eq["customEqFrequency"]
        touch = touch_by_product_id.get(entry["productId"])
        if touch is not None:
            matched_touch += 1
            entry["touchSupport"] = touch
        lines.append(f"  {json.dumps(entry, ensure_ascii=False)},\n")
    lines.append(FOOTER)
    OUTPUT.write_text("".join(lines), encoding="utf-8")
    print(f"Wrote {len(data['devices'])} entries to {OUTPUT} "
          f"({matched_anc} HeyTap + {matched_realme} realme with noiseReductionMode, "
          f"{matched_eq} with EQ modes, {matched_touch} with touch masks)")


if __name__ == "__main__":
    main()
