#!/usr/bin/env python3
"""Regenerate src/drivers/heymelody/catalog.generated.ts from
docs/reference/heymelody-devices.json and docs/reference/heymelody-anc-modes.json.

Source: the 137-device productId/name/brand/type catalog extracted from
OppoPodsManager's bundled DeviceModels.json and cross-validated against
HeyTap's own whitelist resource (see the android-testing repo's
heytap/HEYMELODY_PROTOCOL_NOTES.md §4). Brand casing in the source is
inconsistent ("oppo"/"realme"/"OnePlus") — normalised to lowercase here so
the generated type is a clean 3-value union.

`heymelody-anc-modes.json` is a second, separate source: each model's
`function.noiseReductionMode` array from the same whitelist resource
(`heytap/whitelist_extraction/heymelody_app_whitelist_compat.json`'s
`compatWhiteList`), extracted for the 41/82 whitelist entries that carry it —
this is what tells a driver which bit (`protocolIndex`) to set for which named
ANC mode on a *given* model, since that bit position is not fixed across
models (see `src/drivers/heymelody/ancModel.ts`, ported from
Leaf-lsgtky/OppoPods's `DeviceModelRegistry.buildAncOptions`). Only 81/82
whitelist productIds overlap the 137-device catalog; the one that doesn't is
silently skipped here rather than fabricating a catalog entry for it.

Usage:
    python3 scripts/gen-heymelody-catalog.py
"""

import json
from pathlib import Path

SOURCE = Path("docs/reference/heymelody-devices.json")
ANC_MODES_SOURCE = Path("docs/reference/heymelody-anc-modes.json")
OUTPUT = Path("src/drivers/heymelody/catalog.generated.ts")

HEADER = """/**
 * Generated by scripts/gen-heymelody-catalog.py from
 * docs/reference/heymelody-devices.json and
 * docs/reference/heymelody-anc-modes.json. Do not hand-edit.
 */

import type { RawAncModeEntry } from './ancModel'

export interface HeyMelodyCatalogEntry {
  productId: string
  name: string
  brand: 'oppo' | 'realme' | 'oneplus'
  type: string
  /** Only present for the subset of models the source whitelist covers (see
   * this file's own generator script for provenance) — absent, not an empty
   * array, when this model's ANC bit layout was never captured. */
  noiseReductionMode?: RawAncModeEntry[]
}

export const HEYMELODY_CATALOG: readonly HeyMelodyCatalogEntry[] = [
"""

FOOTER = """]
"""


def main() -> None:
    data = json.loads(SOURCE.read_text(encoding="utf-8"))
    anc_data = json.loads(ANC_MODES_SOURCE.read_text(encoding="utf-8"))
    anc_by_product_id = {d["productId"]: d["noiseReductionMode"] for d in anc_data["devices"]}

    lines = [HEADER]
    matched_anc = 0
    for device in data["devices"]:
        brand = device["brand"].lower()
        entry = {
            "productId": device["productId"],
            "name": device["name"],
            "brand": brand,
            "type": device["type"],
        }
        nrm = anc_by_product_id.get(entry["productId"])
        if nrm is not None:
            entry["noiseReductionMode"] = nrm
            matched_anc += 1
        lines.append(f"  {json.dumps(entry, ensure_ascii=False)},\n")
    lines.append(FOOTER)
    OUTPUT.write_text("".join(lines), encoding="utf-8")
    print(f"Wrote {len(data['devices'])} entries to {OUTPUT} ({matched_anc} with noiseReductionMode)")


if __name__ == "__main__":
    main()
