#!/usr/bin/env python3
"""Regenerate src/drivers/heymelody/catalog.generated.ts from docs/reference/heymelody-devices.json.

Source: the 137-device productId/name/brand/type catalog extracted from
OppoPodsManager's bundled DeviceModels.json and cross-validated against
HeyTap's own whitelist resource (see the android-testing repo's
heytap/HEYMELODY_PROTOCOL_NOTES.md §4). Brand casing in the source is
inconsistent ("oppo"/"realme"/"OnePlus") — normalised to lowercase here so
the generated type is a clean 3-value union.

Usage:
    python3 scripts/gen-heymelody-catalog.py
"""

import json
from pathlib import Path

SOURCE = Path("docs/reference/heymelody-devices.json")
OUTPUT = Path("src/drivers/heymelody/catalog.generated.ts")

HEADER = """/**
 * Generated by scripts/gen-heymelody-catalog.py from
 * docs/reference/heymelody-devices.json. Do not hand-edit.
 */

export interface HeyMelodyCatalogEntry {
  productId: string
  name: string
  brand: 'oppo' | 'realme' | 'oneplus'
  type: string
}

export const HEYMELODY_CATALOG: readonly HeyMelodyCatalogEntry[] = [
"""

FOOTER = """]
"""


def main() -> None:
    data = json.loads(SOURCE.read_text(encoding="utf-8"))
    lines = [HEADER]
    for device in data["devices"]:
        brand = device["brand"].lower()
        entry = {
            "productId": device["productId"],
            "name": device["name"],
            "brand": brand,
            "type": device["type"],
        }
        lines.append(f"  {json.dumps(entry, ensure_ascii=False)},\n")
    lines.append(FOOTER)
    OUTPUT.write_text("".join(lines), encoding="utf-8")
    print(f"Wrote {len(data['devices'])} entries to {OUTPUT}")


if __name__ == "__main__":
    main()
